# Generated by Django 6.0 on 2025-12-14 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Characters',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('height', models.CharField(default='не известно', max_length=10)),
                ('mass', models.CharField(default='не известно', max_length=10)),
                ('hair_color', models.CharField(default='не известно', max_length=50)),
                ('skin_color', models.CharField(default='не известно', max_length=50)),
                ('eye_color', models.CharField(default='не известно', max_length=50)),
                ('birth_year', models.CharField(default='не известно', max_length=20)),
                ('gender', models.CharField(default='не известно', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Starships',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('model', models.CharField(default='не известно', max_length=100)),
                ('manufacturer', models.CharField(default='не известно', max_length=150)),
                ('cost_in_credits', models.CharField(default='не известно', max_length=20)),
                ('length', models.CharField(default='не известно', max_length=20)),
                ('crew', models.CharField(default='не известно', max_length=20)),
                ('passengers', models.CharField(default='не известно', max_length=20)),
            ],
        ),
    ]
