# Generated by Django 6.0 on 2025-12-14 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('characters', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='characters',
            name='starships',
            field=models.ManyToManyField(blank=True, related_name='starships', to='characters.starships'),
        ),
        migrations.AlterField(
            model_name='characters',
            name='name',
            field=models.CharField(db_index=True, max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='starships',
            name='name',
            field=models.CharField(db_index=True, max_length=100, unique=True),
        ),
    ]
