# Generated by Django 6.0 on 2025-12-14 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('characters', '0002_characters_starships_alter_characters_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='characters',
            name='slug',
            field=models.SlugField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='starships',
            name='slug',
            field=models.SlugField(blank=True, max_length=100),
        ),
    ]
