# Generated by Django 6.0 on 2025-12-14 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('characters', '0003_characters_slug_starships_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='characters',
            name='slug',
            field=models.SlugField(blank=True, max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='starships',
            name='slug',
            field=models.SlugField(blank=True, max_length=100, unique=True),
        ),
    ]
